blank_issues_enabled: true
contact_links:
  - name: QuestCraft Website
    url: https://questcraft.org
    about: This is the official QuestCraft website, it contains info on Github, Sidequest, and Discord. 